### ISSUE TITLE
Errors while building examples

### ISSUE THREAD

**Issue by PatCH0816** [paulovap/qtpdfium#24]
I followed the installation instructions in the README file, nevertheless, i get some errors after loading the example project and my attempt to build the project. I'm using Qt5.9 on linux opensuse 42.2.
This is the output:

:-1: Warnung: libicui18n.so.52.1, needed by /opt/Qt5.9/5.9/Src/qtpdfium/lib/libQt5Pdfium.so, may conflict with libicui18n.so.56
:-1: Fehler: /opt/Qt5.9/5.9/Src/qtpdfium/lib/libQt5Pdfium.so: undefined reference to symbol 'ucal_getTimeZoneDisplayName_52_1'
/usr/lib64/libicui18n.so.52.1:-1: Fehler: error adding symbols: DSO missing from command line
:-1: Fehler: collect2: error: ld returned 1 exit status

**Comment by paulovap** [comment]
Can you tell me which version of Qt you tried to build it? Seems like you have two icui library with different versions.

**Comment by PatCH0816** [comment]
Hi Paulo

Thanks for your Support 😊
The Qt Version I used was Qt 5.9.
What are the icui libraries used for?


Best regards from switzerland

Patrick

Gesendet von Mail für Windows 10

Von: Paulo Pinheiro
Gesendet: Freitag, 29. Dezember 2017 12:15
An: paulovap/qtpdfium
Cc: Patrick Koller; Author
Betreff: Re: [paulovap/qtpdfium] Errors while building examples (#24)

Can you tell me which version of Qt you tried to build it? Seems like you have two icui library with different versions.

**Comment by paulovap** [comment]
@Pate0816 icu is needed for extraction of Unicode texts. It is a dependency of pdfium.

If I am not mistaken, depending on how you install Qt it can ship this library or not. If you installed by Qt's Maintenance Tool it probably ships those libraries instead of using the ones in your Linux Distro.

 I would suggest for you to look for this library (`libicui18n.so.56`) in your qt folder or wherever else you think you can find it. And then run the example  binary point to that path using `LD_LIBRARY_PATH`, like this:

```
$ export LD_LIBRARY_PATH="/path/to/icu_folder:/other/needed/path"
$ ./program
```

Tell me if it works!

Best Regards from the Netherlands!
