### ISSUE TITLE
Add text extraction API

### ISSUE THREAD

**Issue by pinaraf** [paulovap/qtpdfium#4]
Hi

This project is great for rendering so far, but it would be really nice to be able to access some text extraction API. For instance, being able to extract the text at a specific location, or every text element of a page.

NB: if I find enough spare time, I'll try to work on this, but I can't promise anything

**Comment by paulovap** [comment]
Hey @pinaraf I am working(very slowly) on updating the pdfium src to the latest version and improving the .pri files. So this may take a while. But it should be easyto add this since the feature already exists on pdfium, just need and API to expose it. I would love to receive contributions.

Thanks!

**Comment by pinaraf** [comment]
Hey

Thanks for that, I will delete my first draft and rebase on your work. I need something a bit finer grained than the text of the whole page and I worked on exposing these APIs too. My PR should come before the week-end.
